### ISSUE TITLE
onDecoded is not firing

### ISSUE THREAD

**Issue by aytunch** [fluttercommunity/flutter_blurhash#26]
We see `onDecoded` in the packages API however It is not connected to the related action at the moment.
There is no instance of `call(widget.onDecoded)`
Could you please add `onDecoded` on both the nullsafe and nullable versions.

**Comment by aytunch** [comment]
I was experimenting and added `widget.onDecoded?.call();` before `Image` is being returned.
I don;t know why but the future builder fires more than once. Maybe it is because the `buildBlurHashBackground` is a `widget function` rather than a `StatelessWidget`. Same with `prepareDisplayedImage`.
Another solution might be to use `decoded` and `decoding` `bool` like the ones used in the code:
```
loaded = false;
loading = false;
```
And inside of the build method we can do
```
if(decoded)
    return Image(image: UiImage(snap.data), fit: widget.imageFit);
```

```
Widget buildBlurHashBackground() => FutureBuilder<ui.Image>(
        future: _image,
        builder: (ctx, snap) {
          if (snap.hasData) {
            print("onDecoded hash:${widget.hash}");
            widget.onDecoded?.call(); //This gets called for more than once per widget.
            return Image(image: UiImage(snap.data), fit: widget.imageFit);
          } else {
            return Container(color: widget.color);
          }
        },
      );
}
```

**Comment by Solido** [comment]
Hi,
onDecoded and onDisplayed events have been added.
Thx
