### ISSUE TITLE
BlurHash widget does not have an error attribute

### ISSUE THREAD

**Issue by sentd94** [fluttercommunity/flutter_blurhash#28]
If you run into an exception trying to download the image (e.g. connection timeout due to bad connection) a red cross with the error message will be shown ontop of the blurhash image. Currently there is no way to disable this behaviour (I'd rather stick with the blur hash over having this ugly cross) or to set a custom error image.

**Comment by girish54321** [comment]
Try this @sentd94 [Link](https://github.com/fluttercommunity/flutter_blurhash/issues/23#issuecomment-829979430)

**Comment by Solido** [comment]
Thx @girish54321 this is the right approach.

**Comment by girish54321** [comment]
Yes this is better @Solido
