### ISSUE TITLE
How to get hash

### ISSUE THREAD

**Issue by herowws** [fluttercommunity/flutter_blurhash#36]
How to get hash

**Comment by romatallinn** [comment]
Usually, you probably want to hash the image on the backend side. You can find different packages that can be used [HERE](https://github.com/woltapp/blurhash#implementations). This plugin doesn't seem to implement this functionality. It's just an decoder.

In the link above, you can also find encoder implementations for Swift and Kotlin, so I guess you can use them. Although it may take some work to integrate them into Flutter by yourself.

**Comment by elkhalifte** [comment]
Here is your answer [Link](https://github.com/justacid/blurhash-dart)

**Comment by Solido** [comment]
You are right. Thanks for pointing to a Dart encoder as I currently only support decoding.
Encoding is a expensive task and should be optimized and the C impl can be easily integrated leading to top perfs and costs.
