### ISSUE TITLE
[Feature] add header for download image

### ISSUE THREAD

**Issue by beerline** [fluttercommunity/flutter_blurhash#41]
Hi, and thank u for such a good library! 

In my case image on server protected by auth token which should be passed in the Header. 
Since  blurhash used `Image.network` under the hood now it is impossible to pass token. 

Seems like to reach this goal at the `BlurHashState.prepareDisplayedImage` instead of `Image.network` we need use: 

```
Image(
    image: NetworkImage(
    imagePath,
    headers: {
      HttpHeaders.authorizationHeader: 'token',
    },
),
```

Let me know what u thinking and i can help with implementation

**Comment by Robert-Scub** [comment]
Oh this is an interesting case!
We should be able to pass an optional Headers paramaters.
Would it be enough for you?

**Comment by Solido** [comment]
Pushed on 0.6.6 @beerline
