### ISSUE TITLE
Version 0.6.6 -  Huge memory consumption and Crash

### ISSUE THREAD

**Issue by YDA93** [fluttercommunity/flutter_blurhash#45]
After Upgrading from 0.6.4 to 0.6.6, 

I noticed huge lag while scrolling into multiple images that use BlurHash as loading widget.

I also noticed significant memory consumption and multiple _spawn stacks being generated.

Reverting back to 0.6.4 fixes the issue.

**Comment by Solido** [comment]
Thank you for the issue. This may be related to the use of isolate to decode the image.
Surely it should leak somewhere. I must find time to check this asap!

**Comment by Solido** [comment]
Rolled back to previous method while I dig into this problem.
0.6.7
