### ISSUE TITLE
Project Update Inquiry

### ISSUE THREAD

**Issue by vtisnado** [fluttercommunity/flutter_blurhash#62]
Hello everyone,

Just wanted to give you a heads up that it's been over a year since the project received an update, and the most recent version was released in April 2022. I'm keen to learn about any upcoming plans for the project or if there are opportunities to the community to contribute to its further development.

I appreciate your commitment to this project!

**Comment by Solido** [comment]
Yes the project has been on hold coupled with missing notifications.
It has been updated today and notifications are up again.
Thanks!
